In [7]:
import pandas as pd

In [8]:
df = pd.read_csv("student_scores.csv")
df.head(10)

   StudentID          Name  Gender           Subject  Score
0          1  Student_0001    Male       Mathematics   59.0
1          2  Student_0002  Female       Mathematics   77.0
2          3  Student_0003    Male       Mathematics   89.0
3          4  Student_0004    Male    Social Studies   82.0
4          5  Student_0005    Male  Computer Science   69.0
5          6  Student_0006  Female    Social Studies   58.0
6          7  Student_0007    Male  Computer Science   78.0
7          8  Student_0008    Male    Social Studies   74.0
8          9  Student_0009    Male    Social Studies   81.0
9         10  Student_0010  Female           English   78.0

In [9]:
df.shape

(1000, 5)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  1000 non-null   int64
 1   Name       1000 non-null   object
 2   Gender     1000 non-null   object
 3   Subject    1000 non-null   object
 4   Score      980 non-null    float64
dtypes: float64(1), int64(1), object(3)
memory usage: 39.2+ KB

In [11]:
df.describe()

         StudentID       Score
count  1000.000000  980.000000
mean    500.500000   68.879592
std     288.819436   14.757758
min       1.000000   24.000000
25%     250.750000   59.000000
50%     500.500000   69.000000
75%     750.250000   79.000000
max    1000.000000  100.000000

In [12]:
df.isnull().sum()

StudentID     0
Name          0
Gender        0
Subject       0
Score        20
dtype: int64

In [13]:
df = df.dropna(subset=["Score"])

In [14]:
df.isnull().sum()

StudentID    0
Name         0
Gender       0
Subject      0
Score        0
dtype: int64

In [15]:
df["Grade"] = df["Score"].apply(
    lambda x: "Pass" if x >= 40 else "Fail"
)

In [16]:
df.head(10)

   StudentID          Name  Gender           Subject  Score Grade
0          1  Student_0001    Male       Mathematics   59.0  Pass
1          2  Student_0002  Female       Mathematics   77.0  Pass
2          3  Student_0003    Male       Mathematics   89.0  Pass
3          4  Student_0004    Male    Social Studies   82.0  Pass
4          5  Student_0005    Male  Computer Science   69.0  Pass
5          6  Student_0006  Female    Social Studies   58.0  Pass
6          7  Student_0007    Male  Computer Science   78.0  Pass
7          8  Student_0008    Male    Social Studies   74.0  Pass
8          9  Student_0009    Male    Social Studies   81.0  Pass
9         10  Student_0010  Female           English   78.0  Pass

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
Top_Students = df[df["Score"] >= 90]

Top_Students

     StudentID          Name  Gender           Subject  Score Grade
14          15  Student_0015  Female       Mathematics   99.0  Pass
16          17  Student_0017  Female           Science   94.0  Pass
25          26  Student_0026  Female           English  100.0  Pass
26          27  Student_0027  Female    Social Studies   94.0  Pass
37          38  Student_0038    Male       Mathematics   92.0  Pass
..         ...           ...     ...               ...    ...   ...
913        914  Student_0914  Female  Computer Science  100.0  Pass
926        927  Student_0927    Male  Computer Science   99.0  Pass
931        932  Student_0932  Female       Mathematics   97.0  Pass
936        937  Student_0937  Female  Computer Science  100.0  Pass
959        960  Student_0960    Male  Computer Science  100.0  Pass

[83 rows x 6 columns]

In [19]:
Top_Students[["StudentID", "Name", "Subject", "Score", "Grade"]]

     StudentID          Name           Subject  Score Grade
14          15  Student_0015       Mathematics   99.0  Pass
16          17  Student_0017           Science   94.0  Pass
25          26  Student_0026           English  100.0  Pass
26          27  Student_0027    Social Studies   94.0  Pass
37          38  Student_0038       Mathematics   92.0  Pass
..         ...           ...               ...    ...   ...
913        914  Student_0914  Computer Science  100.0  Pass
926        927  Student_0927  Computer Science   99.0  Pass
931        932  Student_0932       Mathematics   97.0  Pass
936        937  Student_0937  Computer Science  100.0  Pass
959        960  Student_0960  Computer Science  100.0  Pass

[83 rows x 5 columns]

In [21]:
len(Top_Students)

83

In [24]:
average_score = df.groupby("Subject")["Score"].mean().sort_values(ascending=False)
average_score

Subject
Mathematics         69.705314
Social Studies      69.102941
Science             68.812183
English             68.384236
Computer Science    68.272189
Name: Score, dtype: float64

In [25]:
gender_score = df.groupby("Gender")["Score"].agg(["mean","min","max"])
gender_score

             mean   min    max
Gender
Female  69.174699  24.0  100.0
Male    68.574689  24.0  100.0

In [27]:
subject_count = df["Subject"].value_counts()
subject_count

Subject
Mathematics         207
Social Studies      204
English             203
Science             197
Computer Science    169
Name: count, dtype: int64

In [31]:
df.to_csv("cleaned_students.csv,index=False")
print("Cleaned dataset exported successfully!")

Cleaned dataset exported successfully!

In [32]:
df.head(10)

   StudentID          Name  Gender           Subject  Score Grade
0          1  Student_0001    Male       Mathematics   59.0  Pass
1          2  Student_0002  Female       Mathematics   77.0  Pass
2          3  Student_0003    Male       Mathematics   89.0  Pass
3          4  Student_0004    Male    Social Studies   82.0  Pass
4          5  Student_0005    Male  Computer Science   69.0  Pass
5          6  Student_0006  Female    Social Studies   58.0  Pass
6          7  Student_0007    Male  Computer Science   78.0  Pass
7          8  Student_0008    Male    Social Studies   74.0  Pass
8          9  Student_0009    Male    Social Studies   81.0  Pass
9         10  Student_0010  Female           English   78.0  Pass

In [34]:
subject_summary = df.groupby("Subject")["Score"].mean()
subject_summary

Subject
Computer Science    68.272189
English             68.384236
Mathematics         69.705314
Science             68.812183
Social Studies      69.102941
Name: Score, dtype: float64

In [35]:
subject_summary.to_excel("subject_summary.xlsx")

print("Subject summary exported successfully!")

Subject summary exported successfully!

In [36]:
subject_summary

Subject
Computer Science    68.272189
English             68.384236
Mathematics         69.705314
Science             68.812183
Social Studies      69.102941
Name: Score, dtype: float64

In [ ]:
## Key Findings

1. The average score was calculated for each subject.
2. Students scoring 90 or above were identified using filtering.
3. The cleaned dataset was exported successfully to CSV, and the subject summary was exported to Excel.